
[ArmorConfig]

	#Changing armor values requires world restart
	[ArmorConfig.allthemodium]
		#Allthemodium's Armor Values, in the form of [boots, leggings, chestplate, helmet]. Default: [4, 7, 9, 4]
		armorValues = [4, 7, 9, 4]
		#Allthemodium's Armor Toughness. Default: 4
		toughness = 4
		#Allthemodium's Knockback Resistance. Default: 0.0
		knockbackResistance = 0.0
		#Allthemodium's Max Mana. Default: 200
		maxMana = 200
		#Allthemodium's Spell Power. Default: 0.2 (+20%)
		spellPower = 0.2
		#Allthemodium's Mana Regen. Default: 0.05 (+5%)
		manaRegen = 0.05

	[ArmorConfig.vibranium]
		#Vibranium's Armor Values, in the form of [boots, leggings, chestplate, helmet]. Default: [6, 9, 11, 6]
		armorValues = [6, 9, 11, 6]
		#Vibranium's Armor Toughness. Default: 5
		toughness = 5
		#Vibranium's Knockback Resistance. Default: 0.0
		knockbackResistance = 0.0
		#Vibranium's Max Mana. Default: 325
		maxMana = 325
		#Vibranium's Spell Power. Default: 0.3 (+30%)
		spellPower = 0.3
		#Vibranium's Mana Regen. Default: 0.1 (+10%)
		manaRegen = 0.1

	[ArmorConfig.unobtainium]
		#Unobtainium's Armor Values, in the form of [boots, leggings, chestplate, helmet]. Default: [8, 11, 13, 8]
		armorValues = [8, 11, 13, 8]
		#Unobtainium's Armor Toughness. Default: 6
		toughness = 6
		#Unobtainium's Knockback Resistance. Default: 0.0
		knockbackResistance = 0.0
		#Unobtainium's Max Mana. Default: 450
		maxMana = 450
		#Unobtainium's Spell Power. Default: 0.4 (+40%)
		spellPower = 0.4
		#Unobtainium's Mana Regen. Default: 0.15 (+15%)
		manaRegen = 0.15

